/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiV1DetectorsSearchGet200ResponseInnerTraining from './ApiV1DetectorsSearchGet200ResponseInnerTraining';

/**
 * The ApiV1DetectorsSearchGet200ResponseInner model module.
 * @module model/ApiV1DetectorsSearchGet200ResponseInner
 * @version 1.0.0
 */
class ApiV1DetectorsSearchGet200ResponseInner {
    /**
     * Constructs a new <code>ApiV1DetectorsSearchGet200ResponseInner</code>.
     * @alias module:model/ApiV1DetectorsSearchGet200ResponseInner
     */
    constructor() { 
        
        ApiV1DetectorsSearchGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['state'] = 'trained';
    }

    /**
     * Constructs a <code>ApiV1DetectorsSearchGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1DetectorsSearchGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ApiV1DetectorsSearchGet200ResponseInner} The populated <code>ApiV1DetectorsSearchGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1DetectorsSearchGet200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], ['String']);
            }
            if (data.hasOwnProperty('labelIds')) {
                obj['labelIds'] = ApiClient.convertToType(data['labelIds'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('permissionLevel')) {
                obj['permissionLevel'] = ApiClient.convertToType(data['permissionLevel'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'Boolean');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('processing')) {
                obj['processing'] = ApiClient.convertToType(data['processing'], 'Boolean');
            }
            if (data.hasOwnProperty('training')) {
                obj['training'] = ApiV1DetectorsSearchGet200ResponseInnerTraining.constructFromObject(data['training']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1DetectorsSearchGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1DetectorsSearchGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['labels'])) {
            throw new Error("Expected the field `labels` to be an array in the JSON data but got " + data['labels']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['labelIds'])) {
            throw new Error("Expected the field `labelIds` to be an array in the JSON data but got " + data['labelIds']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['permissionLevel'] && !(typeof data['permissionLevel'] === 'string' || data['permissionLevel'] instanceof String)) {
            throw new Error("Expected the field `permissionLevel` to be a primitive type in the JSON string but got " + data['permissionLevel']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // validate the optional field `training`
        if (data['training']) { // data not null
          ApiV1DetectorsSearchGet200ResponseInnerTraining.validateJSON(data['training']);
        }

        return true;
    }


}



/**
 * Unique ID of the detector
 * @member {String} id
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['id'] = undefined;

/**
 * Name of the detector
 * @member {String} name
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['name'] = undefined;

/**
 * List of label names associated with the detector
 * @member {Array.<String>} labels
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['labels'] = undefined;

/**
 * List of label IDs associated with the detector
 * @member {Array.<String>} labelIds
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['labelIds'] = undefined;

/**
 * Type of the detector
 * @member {String} type
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['type'] = undefined;

/**
 * Permission level of the detector
 * @member {String} permissionLevel
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['permissionLevel'] = undefined;

/**
 * Whether the detector is owned by the user who sent the request
 * @member {Boolean} owner
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['owner'] = undefined;

/**
 * State of the detector
 * @member {String} state
 * @default 'trained'
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['state'] = 'trained';

/**
 * Whether the detector is being updated in the background
 * @member {Boolean} processing
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['processing'] = undefined;

/**
 * @member {module:model/ApiV1DetectorsSearchGet200ResponseInnerTraining} training
 */
ApiV1DetectorsSearchGet200ResponseInner.prototype['training'] = undefined;






export default ApiV1DetectorsSearchGet200ResponseInner;

