/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiV1StreamsPostRequestCustomFieldsInner from './ApiV1StreamsPostRequestCustomFieldsInner';

/**
 * The ApiV1StreamsPostRequest model module.
 * @module model/ApiV1StreamsPostRequest
 * @version 1.0.0
 */
class ApiV1StreamsPostRequest {
    /**
     * Constructs a new <code>ApiV1StreamsPostRequest</code>.
     * @alias module:model/ApiV1StreamsPostRequest
     * @param url {String} URL of the stream
     * @param name {String} Name of the stream
     */
    constructor(url, name) { 
        
        ApiV1StreamsPostRequest.initialize(this, url, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, name) { 
        obj['url'] = url;
        obj['name'] = name;
        obj['detectionFps'] = 1;
        obj['recordingEnabled'] = true;
        obj['retentionDays'] = 7;
    }

    /**
     * Constructs a <code>ApiV1StreamsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1StreamsPostRequest} obj Optional instance to populate.
     * @return {module:model/ApiV1StreamsPostRequest} The populated <code>ApiV1StreamsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1StreamsPostRequest();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('detectionFps')) {
                obj['detectionFps'] = ApiClient.convertToType(data['detectionFps'], 'Number');
            }
            if (data.hasOwnProperty('recordingEnabled')) {
                obj['recordingEnabled'] = ApiClient.convertToType(data['recordingEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('retentionDays')) {
                obj['retentionDays'] = ApiClient.convertToType(data['retentionDays'], 'Number');
            }
            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], [ApiV1StreamsPostRequestCustomFieldsInner]);
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1StreamsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1StreamsPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiV1StreamsPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['customFields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customFields'])) {
                throw new Error("Expected the field `customFields` to be an array in the JSON data but got " + data['customFields']);
            }
            // validate the optional field `customFields` (array)
            for (const item of data['customFields']) {
                ApiV1StreamsPostRequestCustomFieldsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ApiV1StreamsPostRequest.RequiredProperties = ["url", "name"];

/**
 * URL of the stream
 * @member {String} url
 */
ApiV1StreamsPostRequest.prototype['url'] = undefined;

/**
 * Name of the stream
 * @member {String} name
 */
ApiV1StreamsPostRequest.prototype['name'] = undefined;

/**
 * FPS for detections
 * @member {Number} detectionFps
 * @default 1
 */
ApiV1StreamsPostRequest.prototype['detectionFps'] = 1;

/**
 * Whether to enable recording for the stream
 * @member {Boolean} recordingEnabled
 * @default true
 */
ApiV1StreamsPostRequest.prototype['recordingEnabled'] = true;

/**
 * Number of days to retain stream recording
 * @member {Number} retentionDays
 * @default 7
 */
ApiV1StreamsPostRequest.prototype['retentionDays'] = 7;

/**
 * Custom detection API endpoint push notification fields
 * @member {Array.<module:model/ApiV1StreamsPostRequestCustomFieldsInner>} customFields
 */
ApiV1StreamsPostRequest.prototype['customFields'] = undefined;

/**
 * Latitude of stream location
 * @member {Number} latitude
 */
ApiV1StreamsPostRequest.prototype['latitude'] = undefined;

/**
 * Longitude of stream location
 * @member {Number} longitude
 */
ApiV1StreamsPostRequest.prototype['longitude'] = undefined;






export default ApiV1StreamsPostRequest;

