/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiV1MonitoringsMonitoringIdPutRequestColors from './ApiV1MonitoringsMonitoringIdPutRequestColors';
import ApiV1MonitoringsMonitoringIdPutRequestRegion from './ApiV1MonitoringsMonitoringIdPutRequestRegion';
import ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint from './ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint';
import ApiV1MonitoringsMonitoringIdPutRequestSchedule from './ApiV1MonitoringsMonitoringIdPutRequestSchedule';

/**
 * The ApiV1MonitoringsMonitoringIdPutRequest model module.
 * @module model/ApiV1MonitoringsMonitoringIdPutRequest
 * @version 1.0.0
 */
class ApiV1MonitoringsMonitoringIdPutRequest {
    /**
     * Constructs a new <code>ApiV1MonitoringsMonitoringIdPutRequest</code>.
     * @alias module:model/ApiV1MonitoringsMonitoringIdPutRequest
     */
    constructor() { 
        
        ApiV1MonitoringsMonitoringIdPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1MonitoringsMonitoringIdPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1MonitoringsMonitoringIdPutRequest} obj Optional instance to populate.
     * @return {module:model/ApiV1MonitoringsMonitoringIdPutRequest} The populated <code>ApiV1MonitoringsMonitoringIdPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1MonitoringsMonitoringIdPutRequest();

            if (data.hasOwnProperty('thresholds')) {
                obj['thresholds'] = ApiClient.convertToType(data['thresholds'], {'String': 'Number'});
            }
            if (data.hasOwnProperty('restart')) {
                obj['restart'] = ApiClient.convertToType(data['restart'], 'Boolean');
            }
            if (data.hasOwnProperty('keepEndTime')) {
                obj['keepEndTime'] = ApiClient.convertToType(data['keepEndTime'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('notificationTimezone')) {
                obj['notificationTimezone'] = ApiClient.convertToType(data['notificationTimezone'], 'String');
            }
            if (data.hasOwnProperty('registeredEndpoint')) {
                obj['registeredEndpoint'] = ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint.constructFromObject(data['registeredEndpoint']);
            }
            if (data.hasOwnProperty('rawEndpointMessage')) {
                obj['rawEndpointMessage'] = ApiClient.convertToType(data['rawEndpointMessage'], 'Boolean');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiV1MonitoringsMonitoringIdPutRequestSchedule.constructFromObject(data['schedule']);
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiV1MonitoringsMonitoringIdPutRequestRegion.constructFromObject(data['region']);
            }
            if (data.hasOwnProperty('groupsWithViewAccess')) {
                obj['groupsWithViewAccess'] = ApiClient.convertToType(data['groupsWithViewAccess'], ['String']);
            }
            if (data.hasOwnProperty('colors')) {
                obj['colors'] = ApiV1MonitoringsMonitoringIdPutRequestColors.constructFromObject(data['colors']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1MonitoringsMonitoringIdPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1MonitoringsMonitoringIdPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['notificationTimezone'] && !(typeof data['notificationTimezone'] === 'string' || data['notificationTimezone'] instanceof String)) {
            throw new Error("Expected the field `notificationTimezone` to be a primitive type in the JSON string but got " + data['notificationTimezone']);
        }
        // validate the optional field `registeredEndpoint`
        if (data['registeredEndpoint']) { // data not null
          ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint.validateJSON(data['registeredEndpoint']);
        }
        // validate the optional field `schedule`
        if (data['schedule']) { // data not null
          ApiV1MonitoringsMonitoringIdPutRequestSchedule.validateJSON(data['schedule']);
        }
        // validate the optional field `region`
        if (data['region']) { // data not null
          ApiV1MonitoringsMonitoringIdPutRequestRegion.validateJSON(data['region']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['groupsWithViewAccess'])) {
            throw new Error("Expected the field `groupsWithViewAccess` to be an array in the JSON data but got " + data['groupsWithViewAccess']);
        }
        // validate the optional field `colors`
        if (data['colors']) { // data not null
          ApiV1MonitoringsMonitoringIdPutRequestColors.validateJSON(data['colors']);
        }

        return true;
    }


}



/**
 * Object of label names with corresponding threshold value in range (0, 1]
 * @member {Object.<String, Number>} thresholds
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['thresholds'] = undefined;

/**
 * Whether to restart the monitoring
 * @member {Boolean} restart
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['restart'] = undefined;

/**
 * Whether to maintain the previously scheduled end time for this monitoring
 * @member {Boolean} keepEndTime
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['keepEndTime'] = undefined;

/**
 * Updated name for this monitoring
 * @member {String} name
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['name'] = undefined;

/**
 * Time zone for the scheduling of this monitoring
 * @member {String} notificationTimezone
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['notificationTimezone'] = undefined;

/**
 * @member {module:model/ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint} registeredEndpoint
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['registeredEndpoint'] = undefined;

/**
 * Whether to send raw detection data to registered endpoint by default
 * @member {Boolean} rawEndpointMessage
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['rawEndpointMessage'] = undefined;

/**
 * @member {module:model/ApiV1MonitoringsMonitoringIdPutRequestSchedule} schedule
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['schedule'] = undefined;

/**
 * @member {module:model/ApiV1MonitoringsMonitoringIdPutRequestRegion} region
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['region'] = undefined;

/**
 * User group IDs with view access for this monitoring
 * @member {Array.<String>} groupsWithViewAccess
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['groupsWithViewAccess'] = undefined;

/**
 * @member {module:model/ApiV1MonitoringsMonitoringIdPutRequestColors} colors
 */
ApiV1MonitoringsMonitoringIdPutRequest.prototype['colors'] = undefined;






export default ApiV1MonitoringsMonitoringIdPutRequest;

