/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner from './ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner';

/**
 * The ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner model module.
 * @module model/ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner
 * @version 1.0.0
 */
class ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner {
    /**
     * Constructs a new <code>ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner</code>.
     * @alias module:model/ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner
     */
    constructor() { 
        
        ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner} obj Optional instance to populate.
     * @return {module:model/ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner} The populated <code>ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner();

            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('image_id')) {
                obj['image_id'] = ApiClient.convertToType(data['image_id'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('mediaType')) {
                obj['mediaType'] = ApiClient.convertToType(data['mediaType'], 'String');
            }
            if (data.hasOwnProperty('bboxes_nested')) {
                obj['bboxes_nested'] = ApiClient.convertToType(data['bboxes_nested'], [ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner]);
            }
            if (data.hasOwnProperty('box_num')) {
                obj['box_num'] = ApiClient.convertToType(data['box_num'], 'Number');
            }
            if (data.hasOwnProperty('rank')) {
                obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['media'] && !(typeof data['media'] === 'string' || data['media'] instanceof String)) {
            throw new Error("Expected the field `media` to be a primitive type in the JSON string but got " + data['media']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['mediaType'] && !(typeof data['mediaType'] === 'string' || data['mediaType'] instanceof String)) {
            throw new Error("Expected the field `mediaType` to be a primitive type in the JSON string but got " + data['mediaType']);
        }
        if (data['bboxes_nested']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['bboxes_nested'])) {
                throw new Error("Expected the field `bboxes_nested` to be an array in the JSON data but got " + data['bboxes_nested']);
            }
            // validate the optional field `bboxes_nested` (array)
            for (const item of data['bboxes_nested']) {
                ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Media ID
 * @member {String} media
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['media'] = undefined;

/**
 * Timestamp of the result
 * @member {Number} timestamp
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['timestamp'] = undefined;

/**
 * Image ID
 * @member {Number} image_id
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['image_id'] = undefined;

/**
 * URL of the result media
 * @member {String} url
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['url'] = undefined;

/**
 * Type of media (image/video)
 * @member {String} mediaType
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['mediaType'] = undefined;

/**
 * List of bounding boxes with labels and scores
 * @member {Array.<module:model/ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner>} bboxes_nested
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['bboxes_nested'] = undefined;

/**
 * Box number
 * @member {Number} box_num
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['box_num'] = undefined;

/**
 * Rank of the result
 * @member {Number} rank
 */
ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner.prototype['rank'] = undefined;






export default ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner;

