/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiV1MonitoringsGet200ResponseInnerRegion from './ApiV1MonitoringsGet200ResponseInnerRegion';
import ApiV1MonitoringsGet200ResponseInnerSchedule from './ApiV1MonitoringsGet200ResponseInnerSchedule';

/**
 * The ApiV1MonitoringsGet200ResponseInner model module.
 * @module model/ApiV1MonitoringsGet200ResponseInner
 * @version 1.0.0
 */
class ApiV1MonitoringsGet200ResponseInner {
    /**
     * Constructs a new <code>ApiV1MonitoringsGet200ResponseInner</code>.
     * @alias module:model/ApiV1MonitoringsGet200ResponseInner
     */
    constructor() { 
        
        ApiV1MonitoringsGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1MonitoringsGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1MonitoringsGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ApiV1MonitoringsGet200ResponseInner} The populated <code>ApiV1MonitoringsGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1MonitoringsGet200ResponseInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('monitoringId')) {
                obj['monitoringId'] = ApiClient.convertToType(data['monitoringId'], 'String');
            }
            if (data.hasOwnProperty('streamId')) {
                obj['streamId'] = ApiClient.convertToType(data['streamId'], 'String');
            }
            if (data.hasOwnProperty('detectorId')) {
                obj['detectorId'] = ApiClient.convertToType(data['detectorId'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], ['String']);
            }
            if (data.hasOwnProperty('thresholds')) {
                obj['thresholds'] = ApiClient.convertToType(data['thresholds'], ['Number']);
            }
            if (data.hasOwnProperty('endpoint')) {
                obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiV1MonitoringsGet200ResponseInnerRegion.constructFromObject(data['region']);
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiV1MonitoringsGet200ResponseInnerSchedule.constructFromObject(data['schedule']);
            }
            if (data.hasOwnProperty('permissionLevel')) {
                obj['permissionLevel'] = ApiClient.convertToType(data['permissionLevel'], 'String');
            }
            if (data.hasOwnProperty('lastDetectAt')) {
                obj['lastDetectAt'] = ApiClient.convertToType(data['lastDetectAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1MonitoringsGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1MonitoringsGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['monitoringId'] && !(typeof data['monitoringId'] === 'string' || data['monitoringId'] instanceof String)) {
            throw new Error("Expected the field `monitoringId` to be a primitive type in the JSON string but got " + data['monitoringId']);
        }
        // ensure the json data is a string
        if (data['streamId'] && !(typeof data['streamId'] === 'string' || data['streamId'] instanceof String)) {
            throw new Error("Expected the field `streamId` to be a primitive type in the JSON string but got " + data['streamId']);
        }
        // ensure the json data is a string
        if (data['detectorId'] && !(typeof data['detectorId'] === 'string' || data['detectorId'] instanceof String)) {
            throw new Error("Expected the field `detectorId` to be a primitive type in the JSON string but got " + data['detectorId']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['labels'])) {
            throw new Error("Expected the field `labels` to be an array in the JSON data but got " + data['labels']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['thresholds'])) {
            throw new Error("Expected the field `thresholds` to be an array in the JSON data but got " + data['thresholds']);
        }
        // ensure the json data is a string
        if (data['endpoint'] && !(typeof data['endpoint'] === 'string' || data['endpoint'] instanceof String)) {
            throw new Error("Expected the field `endpoint` to be a primitive type in the JSON string but got " + data['endpoint']);
        }
        // validate the optional field `region`
        if (data['region']) { // data not null
          ApiV1MonitoringsGet200ResponseInnerRegion.validateJSON(data['region']);
        }
        // validate the optional field `schedule`
        if (data['schedule']) { // data not null
          ApiV1MonitoringsGet200ResponseInnerSchedule.validateJSON(data['schedule']);
        }
        // ensure the json data is a string
        if (data['permissionLevel'] && !(typeof data['permissionLevel'] === 'string' || data['permissionLevel'] instanceof String)) {
            throw new Error("Expected the field `permissionLevel` to be a primitive type in the JSON string but got " + data['permissionLevel']);
        }

        return true;
    }


}



/**
 * Name of the monitoring
 * @member {String} name
 */
ApiV1MonitoringsGet200ResponseInner.prototype['name'] = undefined;

/**
 * Unique ID of the monitoring
 * @member {String} monitoringId
 */
ApiV1MonitoringsGet200ResponseInner.prototype['monitoringId'] = undefined;

/**
 * Unique ID of the stream associated with the monitoring
 * @member {String} streamId
 */
ApiV1MonitoringsGet200ResponseInner.prototype['streamId'] = undefined;

/**
 * Unique ID of the detector associated with the monitoring
 * @member {String} detectorId
 */
ApiV1MonitoringsGet200ResponseInner.prototype['detectorId'] = undefined;

/**
 * Current state of the monitoring
 * @member {module:model/ApiV1MonitoringsGet200ResponseInner.StateEnum} state
 */
ApiV1MonitoringsGet200ResponseInner.prototype['state'] = undefined;

/**
 * List of labels to detect
 * @member {Array.<String>} labels
 */
ApiV1MonitoringsGet200ResponseInner.prototype['labels'] = undefined;

/**
 * List of confidence thresholds for each label
 * @member {Array.<Number>} thresholds
 */
ApiV1MonitoringsGet200ResponseInner.prototype['thresholds'] = undefined;

/**
 * Endpoint where detections are sent
 * @member {String} endpoint
 */
ApiV1MonitoringsGet200ResponseInner.prototype['endpoint'] = undefined;

/**
 * @member {module:model/ApiV1MonitoringsGet200ResponseInnerRegion} region
 */
ApiV1MonitoringsGet200ResponseInner.prototype['region'] = undefined;

/**
 * @member {module:model/ApiV1MonitoringsGet200ResponseInnerSchedule} schedule
 */
ApiV1MonitoringsGet200ResponseInner.prototype['schedule'] = undefined;

/**
 * Permission level of the monitoring
 * @member {module:model/ApiV1MonitoringsGet200ResponseInner.PermissionLevelEnum} permissionLevel
 */
ApiV1MonitoringsGet200ResponseInner.prototype['permissionLevel'] = undefined;

/**
 * Timestamp for the last time there was a detection on the stream
 * @member {Date} lastDetectAt
 */
ApiV1MonitoringsGet200ResponseInner.prototype['lastDetectAt'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
ApiV1MonitoringsGet200ResponseInner['StateEnum'] = {

    /**
     * value: "scheduled"
     * @const
     */
    "scheduled": "scheduled",

    /**
     * value: "requested"
     * @const
     */
    "requested": "requested",

    /**
     * value: "toprepare"
     * @const
     */
    "toprepare": "toprepare",

    /**
     * value: "preparing"
     * @const
     */
    "preparing": "preparing",

    /**
     * value: "ready"
     * @const
     */
    "ready": "ready",

    /**
     * value: "success"
     * @const
     */
    "success": "success",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"
};


/**
 * Allowed values for the <code>permissionLevel</code> property.
 * @enum {String}
 * @readonly
 */
ApiV1MonitoringsGet200ResponseInner['PermissionLevelEnum'] = {

    /**
     * value: "private"
     * @const
     */
    "private": "private",

    /**
     * value: "open"
     * @const
     */
    "open": "open"
};



export default ApiV1MonitoringsGet200ResponseInner;

