/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiV1BucketTasksPost400Response from '../model/ApiV1BucketTasksPost400Response';
import ApiV1TestUsersPost200Response from '../model/ApiV1TestUsersPost200Response';
import ApiV1TestUsersUserIdDelete200Response from '../model/ApiV1TestUsersUserIdDelete200Response';

/**
* Users service.
* @module api/UsersApi
* @version 1.0.0
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV1TestUsersPost operation.
     * @callback module:api/UsersApi~apiV1TestUsersPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiV1TestUsersPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create test user
     * Creates a new user. Only accessible by administrators (on-prem).
     * @param {String} firstName User's first name
     * @param {String} lastName User's last name
     * @param {String} email User's email, must be unique
     * @param {String} password User's password
     * @param {String} detectorColumns Comma separated list of detector columns to show on detector page
     * @param {String} planName The user's initial plan
     * @param {Object} opts Optional parameters
     * @param {Number} [concurrentTrainLimit] Maximum number of detectors that can be trained simultaneously
     * @param {Number} [concurrentVideoLimit] Maximum number of videos that can be processed simultaneously
     * @param {String} [creditLimit] User credits
     * @param {Boolean} [canAccessStreamDetections] Whether the user can access the calendar page
     * @param {String} [groupList] Comma separated list of groups the user will belong to
     * @param {Boolean} [enableEmail] Whether email should be enabled for the user. Defaults to false
     * @param {module:api/UsersApi~apiV1TestUsersPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiV1TestUsersPost200Response}
     */
    apiV1TestUsersPost(firstName, lastName, email, password, detectorColumns, planName, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'firstName' is set
      if (firstName === undefined || firstName === null) {
        throw new Error("Missing the required parameter 'firstName' when calling apiV1TestUsersPost");
      }
      // verify the required parameter 'lastName' is set
      if (lastName === undefined || lastName === null) {
        throw new Error("Missing the required parameter 'lastName' when calling apiV1TestUsersPost");
      }
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling apiV1TestUsersPost");
      }
      // verify the required parameter 'password' is set
      if (password === undefined || password === null) {
        throw new Error("Missing the required parameter 'password' when calling apiV1TestUsersPost");
      }
      // verify the required parameter 'detectorColumns' is set
      if (detectorColumns === undefined || detectorColumns === null) {
        throw new Error("Missing the required parameter 'detectorColumns' when calling apiV1TestUsersPost");
      }
      // verify the required parameter 'planName' is set
      if (planName === undefined || planName === null) {
        throw new Error("Missing the required parameter 'planName' when calling apiV1TestUsersPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'firstName': firstName,
        'lastName': lastName,
        'email': email,
        'password': password,
        'detectorColumns': detectorColumns,
        'concurrentTrainLimit': opts['concurrentTrainLimit'],
        'concurrentVideoLimit': opts['concurrentVideoLimit'],
        'creditLimit': opts['creditLimit'],
        'canAccessStreamDetections': opts['canAccessStreamDetections'],
        'groupList': opts['groupList'],
        'planName': planName,
        'enableEmail': opts['enableEmail']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = ApiV1TestUsersPost200Response;
      return this.apiClient.callApi(
        '/api/v1/test_users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV1TestUsersUserIdDelete operation.
     * @callback module:api/UsersApi~apiV1TestUsersUserIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiV1TestUsersUserIdDelete200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete test user
     * Deletes a user and all associated data
     * @param {String} userId ID of the user to delete
     * @param {module:api/UsersApi~apiV1TestUsersUserIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiV1TestUsersUserIdDelete200Response}
     */
    apiV1TestUsersUserIdDelete(userId, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling apiV1TestUsersUserIdDelete");
      }

      let pathParams = {
        'userId': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ApiV1TestUsersUserIdDelete200Response;
      return this.apiClient.callApi(
        '/api/v1/test_users/{userId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
