/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiV1DetectorsDetectorIdClassifyVideoPost200Response from '../model/ApiV1DetectorsDetectorIdClassifyVideoPost200Response';
import ApiV1VideosVideoIdGet200Response from '../model/ApiV1VideosVideoIdGet200Response';

/**
* Videos service.
* @module api/VideosApi
* @version 1.0.0
*/
export default class VideosApi {

    /**
    * Constructs a new VideosApi. 
    * @alias module:api/VideosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV1DetectorsDetectorIdClassifyVideoPost operation.
     * @callback module:api/VideosApi~apiV1DetectorsDetectorIdClassifyVideoPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiV1DetectorsDetectorIdClassifyVideoPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Classify video
     * Asynchronously classifies a video using a detector. The classification results can be retrieved using the Get Video Results endpoint.
     * @param {String} detectorId Unique ID of the detector with which to classify
     * @param {Object} opts Optional parameters
     * @param {String} [url] URL of a supported video (e.g. Youtube video)
     * @param {String} [videoId] URL and videoId can both be supplied to skip downloading an existing video
     * @param {File} [file] Video file (alternative to url)
     * @param {Number} [fps = 1)] Number of frames per second
     * @param {Object.<String, {String: Number}>} [annotationThresholds] Mapping of label names to confidence thresholds
     * @param {Boolean} [forceReclassify] Whether to force reclassification of the video
     * @param {String} [taskId] Whether to include task ID in response
     * @param {module:api/VideosApi~apiV1DetectorsDetectorIdClassifyVideoPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiV1DetectorsDetectorIdClassifyVideoPost200Response}
     */
    apiV1DetectorsDetectorIdClassifyVideoPost(detectorId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'detectorId' is set
      if (detectorId === undefined || detectorId === null) {
        throw new Error("Missing the required parameter 'detectorId' when calling apiV1DetectorsDetectorIdClassifyVideoPost");
      }

      let pathParams = {
        'detectorId': detectorId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'url': opts['url'],
        'videoId': opts['videoId'],
        'file': opts['file'],
        'fps': opts['fps'],
        'annotationThresholds': opts['annotationThresholds'],
        'forceReclassify': opts['forceReclassify'],
        'task_id': opts['taskId']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = ApiV1DetectorsDetectorIdClassifyVideoPost200Response;
      return this.apiClient.callApi(
        '/api/v1/detectors/{detectorId}/classify_video', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV1VideosVideoIdGet operation.
     * @callback module:api/VideosApi~apiV1VideosVideoIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiV1VideosVideoIdGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get video results
     * Retrieves classification progress and results for a video.
     * @param {String} videoId Unique ID of the video to retrieve results for
     * @param {Object} opts Optional parameters
     * @param {Number} [threshold] Minimum confidence for returned detections
     * @param {module:model/String} [format = 'json')] Format of the results
     * @param {Boolean} [annotations] Whether to include annotations in the response
     * @param {module:api/VideosApi~apiV1VideosVideoIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiV1VideosVideoIdGet200Response}
     */
    apiV1VideosVideoIdGet(videoId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling apiV1VideosVideoIdGet");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
        'threshold': opts['threshold'],
        'format': opts['format'],
        'annotations': opts['annotations']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/csv'];
      let returnType = ApiV1VideosVideoIdGet200Response;
      return this.apiClient.callApi(
        '/api/v1/videos/{videoId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
