/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MatroidPublicApi);
  }
}(this, function(expect, MatroidPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiV1BucketTasksPost200ResponseCollectionTask', function() {
    it('should create an instance of ApiV1BucketTasksPost200ResponseCollectionTask', function() {
      // uncomment below and update the code to test ApiV1BucketTasksPost200ResponseCollectionTask
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be.a(MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property network (base name: "network")', function() {
      // uncomment below and update the code to test the property network
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property collectionToProcess (base name: "collectionToProcess")', function() {
      // uncomment below and update the code to test the property collectionToProcess
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property fileTypes (base name: "fileTypes")', function() {
      // uncomment below and update the code to test the property fileTypes
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property permissionLevel (base name: "permissionLevel")', function() {
      // uncomment below and update the code to test the property permissionLevel
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property queryByScoreEnabled (base name: "queryByScoreEnabled")', function() {
      // uncomment below and update the code to test the property queryByScoreEnabled
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property canQueryLive (base name: "canQueryLive")', function() {
      // uncomment below and update the code to test the property canQueryLive
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property listerChunksize (base name: "listerChunksize")', function() {
      // uncomment below and update the code to test the property listerChunksize
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property imagesetSize (base name: "imagesetSize")', function() {
      // uncomment below and update the code to test the property imagesetSize
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property throttlerFps (base name: "throttlerFps")', function() {
      // uncomment below and update the code to test the property throttlerFps
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property maxRetries (base name: "maxRetries")', function() {
      // uncomment below and update the code to test the property maxRetries
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property maxSubtasks (base name: "maxSubtasks")', function() {
      // uncomment below and update the code to test the property maxSubtasks
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property csvUrl (base name: "csvUrl")', function() {
      // uncomment below and update the code to test the property csvUrl
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property makeCsv (base name: "makeCsv")', function() {
      // uncomment below and update the code to test the property makeCsv
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property indexerInfo (base name: "indexerInfo")', function() {
      // uncomment below and update the code to test the property indexerInfo
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property runLastLayer (base name: "runLastLayer")', function() {
      // uncomment below and update the code to test the property runLastLayer
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property runBottleneck (base name: "runBottleneck")', function() {
      // uncomment below and update the code to test the property runBottleneck
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property videoFrameFps (base name: "videoFrameFps")', function() {
      // uncomment below and update the code to test the property videoFrameFps
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property outOfCredits (base name: "outOfCredits")', function() {
      // uncomment below and update the code to test the property outOfCredits
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property killedByUser (base name: "killedByUser")', function() {
      // uncomment below and update the code to test the property killedByUser
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property kill (base name: "kill")', function() {
      // uncomment below and update the code to test the property kill
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property isUpdate (base name: "isUpdate")', function() {
      // uncomment below and update the code to test the property isUpdate
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MatroidPublicApi.ApiV1BucketTasksPost200ResponseCollectionTask();
      //expect(instance).to.be();
    });

  });

}));
