/**
 * Matroid Public API
 * The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  ``` Authorization: Bearer YOUR_API_KEY ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiV1AccountGet200Response from './model/ApiV1AccountGet200Response';
import ApiV1AccountGet200ResponseAccount from './model/ApiV1AccountGet200ResponseAccount';
import ApiV1AccountGet200ResponseAccountCredits from './model/ApiV1AccountGet200ResponseAccountCredits';
import ApiV1AccountGet200ResponseAccountName from './model/ApiV1AccountGet200ResponseAccountName';
import ApiV1BucketTasksPost200Response from './model/ApiV1BucketTasksPost200Response';
import ApiV1BucketTasksPost200ResponseCollectionTask from './model/ApiV1BucketTasksPost200ResponseCollectionTask';
import ApiV1BucketTasksPost400Response from './model/ApiV1BucketTasksPost400Response';
import ApiV1BucketTasksPostRequest from './model/ApiV1BucketTasksPostRequest';
import ApiV1CollectionTasksTaskIdDelete200Response from './model/ApiV1CollectionTasksTaskIdDelete200Response';
import ApiV1CollectionTasksTaskIdGet200Response from './model/ApiV1CollectionTasksTaskIdGet200Response';
import ApiV1CollectionTasksTaskIdGet200ResponseCollectionTask from './model/ApiV1CollectionTasksTaskIdGet200ResponseCollectionTask';
import ApiV1CollectionTasksTaskIdImageQueryPost200Response from './model/ApiV1CollectionTasksTaskIdImageQueryPost200Response';
import ApiV1CollectionTasksTaskIdImageQueryPost200ResponseResultsInner from './model/ApiV1CollectionTasksTaskIdImageQueryPost200ResponseResultsInner';
import ApiV1CollectionTasksTaskIdImageQueryPostRequestBoundingBox from './model/ApiV1CollectionTasksTaskIdImageQueryPostRequestBoundingBox';
import ApiV1CollectionTasksTaskIdKillPost200Response from './model/ApiV1CollectionTasksTaskIdKillPost200Response';
import ApiV1CollectionTasksTaskIdKillPost200ResponseCollection from './model/ApiV1CollectionTasksTaskIdKillPost200ResponseCollection';
import ApiV1CollectionTasksTaskIdPut200Response from './model/ApiV1CollectionTasksTaskIdPut200Response';
import ApiV1CollectionTasksTaskIdPutRequest from './model/ApiV1CollectionTasksTaskIdPutRequest';
import ApiV1CollectionTasksTaskIdScoresQueryPost200Response from './model/ApiV1CollectionTasksTaskIdScoresQueryPost200Response';
import ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInner from './model/ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInner';
import ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner from './model/ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner';
import ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInnerLabelsInner from './model/ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInnerLabelsInner';
import ApiV1CollectionTasksTaskIdScoresQueryPostRequest from './model/ApiV1CollectionTasksTaskIdScoresQueryPostRequest';
import ApiV1CollectionTasksTaskIdTextQueryPost200Response from './model/ApiV1CollectionTasksTaskIdTextQueryPost200Response';
import ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner from './model/ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner';
import ApiV1CollectionsCollectionIdCollectionTasksPost200Response from './model/ApiV1CollectionsCollectionIdCollectionTasksPost200Response';
import ApiV1CollectionsCollectionIdDelete200Response from './model/ApiV1CollectionsCollectionIdDelete200Response';
import ApiV1CollectionsCollectionIdGet200Response from './model/ApiV1CollectionsCollectionIdGet200Response';
import ApiV1CollectionsCollectionIdGet200ResponseCollection from './model/ApiV1CollectionsCollectionIdGet200ResponseCollection';
import ApiV1CollectionsCollectionIdGet200ResponseCollectionTasksInner from './model/ApiV1CollectionsCollectionIdGet200ResponseCollectionTasksInner';
import ApiV1CollectionsPost200Response from './model/ApiV1CollectionsPost200Response';
import ApiV1DetectorsDetectorIdClassifyImagePost200Response from './model/ApiV1DetectorsDetectorIdClassifyImagePost200Response';
import ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInner from './model/ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInner';
import ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInner from './model/ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInner';
import ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInnerBoundingBox from './model/ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInnerBoundingBox';
import ApiV1DetectorsDetectorIdClassifyVideoPost200Response from './model/ApiV1DetectorsDetectorIdClassifyVideoPost200Response';
import ApiV1DetectorsDetectorIdDelete200Response from './model/ApiV1DetectorsDetectorIdDelete200Response';
import ApiV1DetectorsDetectorIdFeedbackFeedbackIdDelete200Response from './model/ApiV1DetectorsDetectorIdFeedbackFeedbackIdDelete200Response';
import ApiV1DetectorsDetectorIdFeedbackGet200ResponseInner from './model/ApiV1DetectorsDetectorIdFeedbackGet200ResponseInner';
import ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf from './model/ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf';
import ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf1 from './model/ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf1';
import ApiV1DetectorsDetectorIdFeedbackImagePost200Response from './model/ApiV1DetectorsDetectorIdFeedbackImagePost200Response';
import ApiV1DetectorsDetectorIdFeedbackPost200Response from './model/ApiV1DetectorsDetectorIdFeedbackPost200Response';
import ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInner from './model/ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInner';
import ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInnerBoundingBox from './model/ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInnerBoundingBox';
import ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInner from './model/ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInner';
import ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInnerBoundingBox from './model/ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInnerBoundingBox';
import ApiV1DetectorsDetectorIdFinalizePost200Response from './model/ApiV1DetectorsDetectorIdFinalizePost200Response';
import ApiV1DetectorsDetectorIdGet200Response from './model/ApiV1DetectorsDetectorIdGet200Response';
import ApiV1DetectorsDetectorIdGet200ResponseTraining from './model/ApiV1DetectorsDetectorIdGet200ResponseTraining';
import ApiV1DetectorsDetectorIdGetSaliencyMapPost200Response from './model/ApiV1DetectorsDetectorIdGetSaliencyMapPost200Response';
import ApiV1DetectorsDetectorIdLabelsLabelIdDelete200Response from './model/ApiV1DetectorsDetectorIdLabelsLabelIdDelete200Response';
import ApiV1DetectorsDetectorIdLabelsLabelIdGet200Response from './model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200Response';
import ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInner from './model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInner';
import ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInner from './model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInner';
import ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInnerBbox from './model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInnerBbox';
import ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequest from './model/ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequest';
import ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInner from './model/ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInner';
import ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInnerBbox from './model/ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInnerBbox';
import ApiV1DetectorsDetectorIdLabelsPost200Response from './model/ApiV1DetectorsDetectorIdLabelsPost200Response';
import ApiV1DetectorsDetectorIdMigrateDownPut200Response from './model/ApiV1DetectorsDetectorIdMigrateDownPut200Response';
import ApiV1DetectorsDetectorIdMigratePut200Response from './model/ApiV1DetectorsDetectorIdMigratePut200Response';
import ApiV1DetectorsDetectorIdRedoPost200Response from './model/ApiV1DetectorsDetectorIdRedoPost200Response';
import ApiV1DetectorsGet200ResponseInner from './model/ApiV1DetectorsGet200ResponseInner';
import ApiV1DetectorsSearchGet200ResponseInner from './model/ApiV1DetectorsSearchGet200ResponseInner';
import ApiV1DetectorsSearchGet200ResponseInnerTraining from './model/ApiV1DetectorsSearchGet200ResponseInnerTraining';
import ApiV1DetectorsUploadPost200Response from './model/ApiV1DetectorsUploadPost200Response';
import ApiV1ImagesAnnotationsGet200Response from './model/ApiV1ImagesAnnotationsGet200Response';
import ApiV1ImagesAnnotationsGet200ResponseAnnotationsInner from './model/ApiV1ImagesAnnotationsGet200ResponseAnnotationsInner';
import ApiV1ImagesAnnotationsGet200ResponseAnnotationsInnerTagsInner from './model/ApiV1ImagesAnnotationsGet200ResponseAnnotationsInnerTagsInner';
import ApiV1LicensePost200Response from './model/ApiV1LicensePost200Response';
import ApiV1LocalizePost200Response from './model/ApiV1LocalizePost200Response';
import ApiV1LocalizePost200ResponseResultsInner from './model/ApiV1LocalizePost200ResponseResultsInner';
import ApiV1LocalizePost200ResponseResultsInnerFileInner from './model/ApiV1LocalizePost200ResponseResultsInnerFileInner';
import ApiV1LocalizePost200ResponseResultsInnerPredictionsInner from './model/ApiV1LocalizePost200ResponseResultsInnerPredictionsInner';
import ApiV1LocalizePost200ResponseResultsInnerPredictionsInnerBbox from './model/ApiV1LocalizePost200ResponseResultsInnerPredictionsInnerBbox';
import ApiV1MonitoringsBatchPut200Response from './model/ApiV1MonitoringsBatchPut200Response';
import ApiV1MonitoringsBatchPut200ResponseModifiedMonitoringsInner from './model/ApiV1MonitoringsBatchPut200ResponseModifiedMonitoringsInner';
import ApiV1MonitoringsBatchPutRequest from './model/ApiV1MonitoringsBatchPutRequest';
import ApiV1MonitoringsBatchPutRequestTaskUpdate from './model/ApiV1MonitoringsBatchPutRequestTaskUpdate';
import ApiV1MonitoringsBatchPutRequestTaskUpdateDetection from './model/ApiV1MonitoringsBatchPutRequestTaskUpdateDetection';
import ApiV1MonitoringsBatchPutRequestTaskUpdateRegisteredEndpoint from './model/ApiV1MonitoringsBatchPutRequestTaskUpdateRegisteredEndpoint';
import ApiV1MonitoringsGet200ResponseInner from './model/ApiV1MonitoringsGet200ResponseInner';
import ApiV1MonitoringsGet200ResponseInnerRegion from './model/ApiV1MonitoringsGet200ResponseInnerRegion';
import ApiV1MonitoringsGet200ResponseInnerSchedule from './model/ApiV1MonitoringsGet200ResponseInnerSchedule';
import ApiV1MonitoringsMonitoringIdDelete200Response from './model/ApiV1MonitoringsMonitoringIdDelete200Response';
import ApiV1MonitoringsMonitoringIdGet200ResponseInner from './model/ApiV1MonitoringsMonitoringIdGet200ResponseInner';
import ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInner from './model/ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInner';
import ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerBbox from './model/ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerBbox';
import ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerScoresInner from './model/ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerScoresInner';
import ApiV1MonitoringsMonitoringIdKillPost200Response from './model/ApiV1MonitoringsMonitoringIdKillPost200Response';
import ApiV1MonitoringsMonitoringIdProcessClipsPost200Response from './model/ApiV1MonitoringsMonitoringIdProcessClipsPost200Response';
import ApiV1MonitoringsMonitoringIdProcessClipsPost200ResponseTemporalTask from './model/ApiV1MonitoringsMonitoringIdProcessClipsPost200ResponseTemporalTask';
import ApiV1MonitoringsMonitoringIdPut200Response from './model/ApiV1MonitoringsMonitoringIdPut200Response';
import ApiV1MonitoringsMonitoringIdPut200ResponseColors from './model/ApiV1MonitoringsMonitoringIdPut200ResponseColors';
import ApiV1MonitoringsMonitoringIdPut200ResponseDetection from './model/ApiV1MonitoringsMonitoringIdPut200ResponseDetection';
import ApiV1MonitoringsMonitoringIdPut200ResponseDetectionMonitoringFilter from './model/ApiV1MonitoringsMonitoringIdPut200ResponseDetectionMonitoringFilter';
import ApiV1MonitoringsMonitoringIdPut200ResponseRegion from './model/ApiV1MonitoringsMonitoringIdPut200ResponseRegion';
import ApiV1MonitoringsMonitoringIdPut200ResponseSchedule from './model/ApiV1MonitoringsMonitoringIdPut200ResponseSchedule';
import ApiV1MonitoringsMonitoringIdPutRequest from './model/ApiV1MonitoringsMonitoringIdPutRequest';
import ApiV1MonitoringsMonitoringIdPutRequestColors from './model/ApiV1MonitoringsMonitoringIdPutRequestColors';
import ApiV1MonitoringsMonitoringIdPutRequestRegion from './model/ApiV1MonitoringsMonitoringIdPutRequestRegion';
import ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint from './model/ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint';
import ApiV1MonitoringsMonitoringIdPutRequestSchedule from './model/ApiV1MonitoringsMonitoringIdPutRequestSchedule';
import ApiV1MonitoringsMonitoringIdWatchGet200Response from './model/ApiV1MonitoringsMonitoringIdWatchGet200Response';
import ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInner from './model/ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInner';
import ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerBbox from './model/ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerBbox';
import ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerScoresInner from './model/ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerScoresInner';
import ApiV1OauthTokenPost200Response from './model/ApiV1OauthTokenPost200Response';
import ApiV1StreamsBatchPost200ResponseValue from './model/ApiV1StreamsBatchPost200ResponseValue';
import ApiV1StreamsBatchPost200ResponseValueMonitoring from './model/ApiV1StreamsBatchPost200ResponseValueMonitoring';
import ApiV1StreamsBatchPost200ResponseValueStream from './model/ApiV1StreamsBatchPost200ResponseValueStream';
import ApiV1StreamsBatchPostRequest1 from './model/ApiV1StreamsBatchPostRequest1';
import ApiV1StreamsBatchPostRequest1DetectorsInner from './model/ApiV1StreamsBatchPostRequest1DetectorsInner';
import ApiV1StreamsBatchPostRequest1StreamsInner from './model/ApiV1StreamsBatchPostRequest1StreamsInner';
import ApiV1StreamsBatchPostRequest1StreamsInnerCustomFieldsInner from './model/ApiV1StreamsBatchPostRequest1StreamsInnerCustomFieldsInner';
import ApiV1StreamsGet200ResponseInner from './model/ApiV1StreamsGet200ResponseInner';
import ApiV1StreamsGet200ResponseInnerRecordingOptions from './model/ApiV1StreamsGet200ResponseInnerRecordingOptions';
import ApiV1StreamsPost200Response from './model/ApiV1StreamsPost200Response';
import ApiV1StreamsPostRequest from './model/ApiV1StreamsPostRequest';
import ApiV1StreamsPostRequestCustomFieldsInner from './model/ApiV1StreamsPostRequestCustomFieldsInner';
import ApiV1StreamsStreamIdClipsGet200Response from './model/ApiV1StreamsStreamIdClipsGet200Response';
import ApiV1StreamsStreamIdClipsGet200ResponseClipsInner from './model/ApiV1StreamsStreamIdClipsGet200ResponseClipsInner';
import ApiV1StreamsStreamIdDelete200Response from './model/ApiV1StreamsStreamIdDelete200Response';
import ApiV1StreamsStreamIdMonitorDetectorIdPost200Response from './model/ApiV1StreamsStreamIdMonitorDetectorIdPost200Response';
import ApiV1StreamsStreamIdMonitorDetectorIdPostRequest from './model/ApiV1StreamsStreamIdMonitorDetectorIdPostRequest';
import ApiV1StreamsStreamIdMonitorDetectorIdPostRequestColors from './model/ApiV1StreamsStreamIdMonitorDetectorIdPostRequestColors';
import ApiV1StreamsStreamIdMonitorDetectorIdPostRequestMonitoringHoursInner from './model/ApiV1StreamsStreamIdMonitorDetectorIdPostRequestMonitoringHoursInner';
import ApiV1StreamsStreamIdPushImagePost200Response from './model/ApiV1StreamsStreamIdPushImagePost200Response';
import ApiV1StreamsStreamIdPushImagePost400Response from './model/ApiV1StreamsStreamIdPushImagePost400Response';
import ApiV1StreamsStreamIdPushVideoPost200Response from './model/ApiV1StreamsStreamIdPushVideoPost200Response';
import ApiV1StreamsStreamIdPut200Response from './model/ApiV1StreamsStreamIdPut200Response';
import ApiV1StreamsStreamIdPut200ResponseCustomFieldsInner from './model/ApiV1StreamsStreamIdPut200ResponseCustomFieldsInner';
import ApiV1StreamsStreamIdPutRequest from './model/ApiV1StreamsStreamIdPutRequest';
import ApiV1StreamsStreamIdPutRequestLocation from './model/ApiV1StreamsStreamIdPutRequestLocation';
import ApiV1StreamsStreamIdSampleStreamPost200Response from './model/ApiV1StreamsStreamIdSampleStreamPost200Response';
import ApiV1StreamsStreamIdSampleStreamPost200ResponseTemporalTask from './model/ApiV1StreamsStreamIdSampleStreamPost200ResponseTemporalTask';
import ApiV1StreamsStreamIdSummariesGet200Response from './model/ApiV1StreamsStreamIdSummariesGet200Response';
import ApiV1StreamsStreamIdSummariesGet200ResponseSummariesInner from './model/ApiV1StreamsStreamIdSummariesGet200ResponseSummariesInner';
import ApiV1StreamsStreamIdSummarizePost200Response from './model/ApiV1StreamsStreamIdSummarizePost200Response';
import ApiV1StreamsStreamIdSummarizePost200ResponseSummary from './model/ApiV1StreamsStreamIdSummarizePost200ResponseSummary';
import ApiV1StreamsStreamIdTemporalTaskPost200Response from './model/ApiV1StreamsStreamIdTemporalTaskPost200Response';
import ApiV1StreamsStreamIdTemporalTasksGet200Response from './model/ApiV1StreamsStreamIdTemporalTasksGet200Response';
import ApiV1StreamsStreamIdTemporalTasksGet200ResponseTemporalTasksInner from './model/ApiV1StreamsStreamIdTemporalTasksGet200ResponseTemporalTasksInner';
import ApiV1SummariesGet200Response from './model/ApiV1SummariesGet200Response';
import ApiV1SummariesGet200ResponseSummariesInner from './model/ApiV1SummariesGet200ResponseSummariesInner';
import ApiV1SummariesSummaryIdDelete200Response from './model/ApiV1SummariesSummaryIdDelete200Response';
import ApiV1SummariesSummaryIdGet200Response from './model/ApiV1SummariesSummaryIdGet200Response';
import ApiV1SystemStatusGet200Response from './model/ApiV1SystemStatusGet200Response';
import ApiV1SystemStatusGet200ResponseDownMonitoringsInner from './model/ApiV1SystemStatusGet200ResponseDownMonitoringsInner';
import ApiV1SystemStatusGet200ResponseDownMonitoringsInnerDetector from './model/ApiV1SystemStatusGet200ResponseDownMonitoringsInnerDetector';
import ApiV1SystemStatusGet200ResponseDownMonitoringsInnerStream from './model/ApiV1SystemStatusGet200ResponseDownMonitoringsInnerStream';
import ApiV1TemporalTasksGet200Response from './model/ApiV1TemporalTasksGet200Response';
import ApiV1TemporalTasksGet200ResponseTemporalTasksInner from './model/ApiV1TemporalTasksGet200ResponseTemporalTasksInner';
import ApiV1TemporalTasksTaskIdDelete200Response from './model/ApiV1TemporalTasksTaskIdDelete200Response';
import ApiV1TemporalTasksTaskIdGet200Response from './model/ApiV1TemporalTasksTaskIdGet200Response';
import ApiV1TemporalTasksTaskIdKillPut200Response from './model/ApiV1TemporalTasksTaskIdKillPut200Response';
import ApiV1TestUsersPost200Response from './model/ApiV1TestUsersPost200Response';
import ApiV1TestUsersUserIdDelete200Response from './model/ApiV1TestUsersUserIdDelete200Response';
import ApiV1VideosVideoIdGet200Response from './model/ApiV1VideosVideoIdGet200Response';
import ApiV1VideosVideoIdGet200ResponseDetectionsValueInner from './model/ApiV1VideosVideoIdGet200ResponseDetectionsValueInner';
import ApiV1VideosVideoIdGet200ResponseDetectionsValueInnerBbox from './model/ApiV1VideosVideoIdGet200ResponseDetectionsValueInnerBbox';
import CreateDetector200Response from './model/CreateDetector200Response';
import AccountsApi from './api/AccountsApi';
import BucketTasksApi from './api/BucketTasksApi';
import DatasetApi from './api/DatasetApi';
import DetectorsApi from './api/DetectorsApi';
import ImagesApi from './api/ImagesApi';
import LabelsApi from './api/LabelsApi';
import LicensesApi from './api/LicensesApi';
import MonitoringsApi from './api/MonitoringsApi';
import OnPremApi from './api/OnPremApi';
import SimilaritySearchApi from './api/SimilaritySearchApi';
import StreamsApi from './api/StreamsApi';
import TemporalTaskApi from './api/TemporalTaskApi';
import UsersApi from './api/UsersApi';
import VideoSummaryApi from './api/VideoSummaryApi';
import VideosApi from './api/VideosApi';


/**
* The Matroid API allows you to easily manipulate and use detectors. You can browse through our fine-tuned detectors, customize detectors with your own images and videos, and even import your own tensorflow models as detectors. Public detectors are available for all of our users, and you can quickly train custom detectors when needed. You can further polish your detectors through our simple web GUI, where you can create composite detectors or topic detectors, give your detectors feedback, and automatically annotate training data.   Once you are happy with your detector, you can use it to classify images, locate objects in videos, and perform real-time detections in live video streams. Create a stream of your camera feed, and you can use our API to get real-time detections from your detector by creating Monitorings. You can also use our API to get the latest detections from your detector, and you can even get the latest detections from a specific time in the past. Feel free to use this documentation page to learn and test out your API requests. But be careful! **Any changes performed may be permanent.**   ## Getting Started  To get started with the Matroid API, you will need to create an account and obtain an API key. You can do this by signing up on our website. Once you have your API key, you can start using the API to create and manage detectors.  ## Authentication  The Matroid API uses bearer token authentication. You will need to include your API key in the Authorization header of your requests. For example:  &#x60;&#x60;&#x60; Authorization: Bearer YOUR_API_KEY &#x60;&#x60;&#x60; .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MatroidPublicApi = require('index'); // See note below*.
* var xxxSvc = new MatroidPublicApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MatroidPublicApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MatroidPublicApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MatroidPublicApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiV1AccountGet200Response model constructor.
     * @property {module:model/ApiV1AccountGet200Response}
     */
    ApiV1AccountGet200Response,

    /**
     * The ApiV1AccountGet200ResponseAccount model constructor.
     * @property {module:model/ApiV1AccountGet200ResponseAccount}
     */
    ApiV1AccountGet200ResponseAccount,

    /**
     * The ApiV1AccountGet200ResponseAccountCredits model constructor.
     * @property {module:model/ApiV1AccountGet200ResponseAccountCredits}
     */
    ApiV1AccountGet200ResponseAccountCredits,

    /**
     * The ApiV1AccountGet200ResponseAccountName model constructor.
     * @property {module:model/ApiV1AccountGet200ResponseAccountName}
     */
    ApiV1AccountGet200ResponseAccountName,

    /**
     * The ApiV1BucketTasksPost200Response model constructor.
     * @property {module:model/ApiV1BucketTasksPost200Response}
     */
    ApiV1BucketTasksPost200Response,

    /**
     * The ApiV1BucketTasksPost200ResponseCollectionTask model constructor.
     * @property {module:model/ApiV1BucketTasksPost200ResponseCollectionTask}
     */
    ApiV1BucketTasksPost200ResponseCollectionTask,

    /**
     * The ApiV1BucketTasksPost400Response model constructor.
     * @property {module:model/ApiV1BucketTasksPost400Response}
     */
    ApiV1BucketTasksPost400Response,

    /**
     * The ApiV1BucketTasksPostRequest model constructor.
     * @property {module:model/ApiV1BucketTasksPostRequest}
     */
    ApiV1BucketTasksPostRequest,

    /**
     * The ApiV1CollectionTasksTaskIdDelete200Response model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdDelete200Response}
     */
    ApiV1CollectionTasksTaskIdDelete200Response,

    /**
     * The ApiV1CollectionTasksTaskIdGet200Response model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdGet200Response}
     */
    ApiV1CollectionTasksTaskIdGet200Response,

    /**
     * The ApiV1CollectionTasksTaskIdGet200ResponseCollectionTask model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdGet200ResponseCollectionTask}
     */
    ApiV1CollectionTasksTaskIdGet200ResponseCollectionTask,

    /**
     * The ApiV1CollectionTasksTaskIdImageQueryPost200Response model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdImageQueryPost200Response}
     */
    ApiV1CollectionTasksTaskIdImageQueryPost200Response,

    /**
     * The ApiV1CollectionTasksTaskIdImageQueryPost200ResponseResultsInner model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdImageQueryPost200ResponseResultsInner}
     */
    ApiV1CollectionTasksTaskIdImageQueryPost200ResponseResultsInner,

    /**
     * The ApiV1CollectionTasksTaskIdImageQueryPostRequestBoundingBox model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdImageQueryPostRequestBoundingBox}
     */
    ApiV1CollectionTasksTaskIdImageQueryPostRequestBoundingBox,

    /**
     * The ApiV1CollectionTasksTaskIdKillPost200Response model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdKillPost200Response}
     */
    ApiV1CollectionTasksTaskIdKillPost200Response,

    /**
     * The ApiV1CollectionTasksTaskIdKillPost200ResponseCollection model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdKillPost200ResponseCollection}
     */
    ApiV1CollectionTasksTaskIdKillPost200ResponseCollection,

    /**
     * The ApiV1CollectionTasksTaskIdPut200Response model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdPut200Response}
     */
    ApiV1CollectionTasksTaskIdPut200Response,

    /**
     * The ApiV1CollectionTasksTaskIdPutRequest model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdPutRequest}
     */
    ApiV1CollectionTasksTaskIdPutRequest,

    /**
     * The ApiV1CollectionTasksTaskIdScoresQueryPost200Response model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdScoresQueryPost200Response}
     */
    ApiV1CollectionTasksTaskIdScoresQueryPost200Response,

    /**
     * The ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInner model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInner}
     */
    ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInner,

    /**
     * The ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner}
     */
    ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInner,

    /**
     * The ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInnerLabelsInner model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInnerLabelsInner}
     */
    ApiV1CollectionTasksTaskIdScoresQueryPost200ResponseResultsInnerBoundingBoxesInnerLabelsInner,

    /**
     * The ApiV1CollectionTasksTaskIdScoresQueryPostRequest model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdScoresQueryPostRequest}
     */
    ApiV1CollectionTasksTaskIdScoresQueryPostRequest,

    /**
     * The ApiV1CollectionTasksTaskIdTextQueryPost200Response model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdTextQueryPost200Response}
     */
    ApiV1CollectionTasksTaskIdTextQueryPost200Response,

    /**
     * The ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner model constructor.
     * @property {module:model/ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner}
     */
    ApiV1CollectionTasksTaskIdTextQueryPost200ResponseResultsInner,

    /**
     * The ApiV1CollectionsCollectionIdCollectionTasksPost200Response model constructor.
     * @property {module:model/ApiV1CollectionsCollectionIdCollectionTasksPost200Response}
     */
    ApiV1CollectionsCollectionIdCollectionTasksPost200Response,

    /**
     * The ApiV1CollectionsCollectionIdDelete200Response model constructor.
     * @property {module:model/ApiV1CollectionsCollectionIdDelete200Response}
     */
    ApiV1CollectionsCollectionIdDelete200Response,

    /**
     * The ApiV1CollectionsCollectionIdGet200Response model constructor.
     * @property {module:model/ApiV1CollectionsCollectionIdGet200Response}
     */
    ApiV1CollectionsCollectionIdGet200Response,

    /**
     * The ApiV1CollectionsCollectionIdGet200ResponseCollection model constructor.
     * @property {module:model/ApiV1CollectionsCollectionIdGet200ResponseCollection}
     */
    ApiV1CollectionsCollectionIdGet200ResponseCollection,

    /**
     * The ApiV1CollectionsCollectionIdGet200ResponseCollectionTasksInner model constructor.
     * @property {module:model/ApiV1CollectionsCollectionIdGet200ResponseCollectionTasksInner}
     */
    ApiV1CollectionsCollectionIdGet200ResponseCollectionTasksInner,

    /**
     * The ApiV1CollectionsPost200Response model constructor.
     * @property {module:model/ApiV1CollectionsPost200Response}
     */
    ApiV1CollectionsPost200Response,

    /**
     * The ApiV1DetectorsDetectorIdClassifyImagePost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdClassifyImagePost200Response}
     */
    ApiV1DetectorsDetectorIdClassifyImagePost200Response,

    /**
     * The ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInner}
     */
    ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInner,

    /**
     * The ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInner}
     */
    ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInner,

    /**
     * The ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInnerBoundingBox model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInnerBoundingBox}
     */
    ApiV1DetectorsDetectorIdClassifyImagePost200ResponsePredictionsInnerClassificationsInnerBoundingBox,

    /**
     * The ApiV1DetectorsDetectorIdClassifyVideoPost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdClassifyVideoPost200Response}
     */
    ApiV1DetectorsDetectorIdClassifyVideoPost200Response,

    /**
     * The ApiV1DetectorsDetectorIdDelete200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdDelete200Response}
     */
    ApiV1DetectorsDetectorIdDelete200Response,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackFeedbackIdDelete200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackFeedbackIdDelete200Response}
     */
    ApiV1DetectorsDetectorIdFeedbackFeedbackIdDelete200Response,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackGet200ResponseInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackGet200ResponseInner}
     */
    ApiV1DetectorsDetectorIdFeedbackGet200ResponseInner,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf}
     */
    ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf1 model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf1}
     */
    ApiV1DetectorsDetectorIdFeedbackGet200ResponseInnerOneOf1,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackImagePost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackImagePost200Response}
     */
    ApiV1DetectorsDetectorIdFeedbackImagePost200Response,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackPost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackPost200Response}
     */
    ApiV1DetectorsDetectorIdFeedbackPost200Response,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInner}
     */
    ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInner,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInnerBoundingBox model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInnerBoundingBox}
     */
    ApiV1DetectorsDetectorIdFeedbackPost200ResponseFeedbackInnerBoundingBox,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInner}
     */
    ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInner,

    /**
     * The ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInnerBoundingBox model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInnerBoundingBox}
     */
    ApiV1DetectorsDetectorIdFeedbackPostRequestFeedbackInnerBoundingBox,

    /**
     * The ApiV1DetectorsDetectorIdFinalizePost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdFinalizePost200Response}
     */
    ApiV1DetectorsDetectorIdFinalizePost200Response,

    /**
     * The ApiV1DetectorsDetectorIdGet200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdGet200Response}
     */
    ApiV1DetectorsDetectorIdGet200Response,

    /**
     * The ApiV1DetectorsDetectorIdGet200ResponseTraining model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdGet200ResponseTraining}
     */
    ApiV1DetectorsDetectorIdGet200ResponseTraining,

    /**
     * The ApiV1DetectorsDetectorIdGetSaliencyMapPost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdGetSaliencyMapPost200Response}
     */
    ApiV1DetectorsDetectorIdGetSaliencyMapPost200Response,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdDelete200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdDelete200Response}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdDelete200Response,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdGet200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200Response}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdGet200Response,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInner}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInner,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInner}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInner,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInnerBbox model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInnerBbox}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdGet200ResponseImagesInnerTagsInnerBbox,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequest model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequest}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequest,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInner model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInner}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInner,

    /**
     * The ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInnerBbox model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInnerBbox}
     */
    ApiV1DetectorsDetectorIdLabelsLabelIdPatchRequestImagesInnerBbox,

    /**
     * The ApiV1DetectorsDetectorIdLabelsPost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdLabelsPost200Response}
     */
    ApiV1DetectorsDetectorIdLabelsPost200Response,

    /**
     * The ApiV1DetectorsDetectorIdMigrateDownPut200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdMigrateDownPut200Response}
     */
    ApiV1DetectorsDetectorIdMigrateDownPut200Response,

    /**
     * The ApiV1DetectorsDetectorIdMigratePut200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdMigratePut200Response}
     */
    ApiV1DetectorsDetectorIdMigratePut200Response,

    /**
     * The ApiV1DetectorsDetectorIdRedoPost200Response model constructor.
     * @property {module:model/ApiV1DetectorsDetectorIdRedoPost200Response}
     */
    ApiV1DetectorsDetectorIdRedoPost200Response,

    /**
     * The ApiV1DetectorsGet200ResponseInner model constructor.
     * @property {module:model/ApiV1DetectorsGet200ResponseInner}
     */
    ApiV1DetectorsGet200ResponseInner,

    /**
     * The ApiV1DetectorsSearchGet200ResponseInner model constructor.
     * @property {module:model/ApiV1DetectorsSearchGet200ResponseInner}
     */
    ApiV1DetectorsSearchGet200ResponseInner,

    /**
     * The ApiV1DetectorsSearchGet200ResponseInnerTraining model constructor.
     * @property {module:model/ApiV1DetectorsSearchGet200ResponseInnerTraining}
     */
    ApiV1DetectorsSearchGet200ResponseInnerTraining,

    /**
     * The ApiV1DetectorsUploadPost200Response model constructor.
     * @property {module:model/ApiV1DetectorsUploadPost200Response}
     */
    ApiV1DetectorsUploadPost200Response,

    /**
     * The ApiV1ImagesAnnotationsGet200Response model constructor.
     * @property {module:model/ApiV1ImagesAnnotationsGet200Response}
     */
    ApiV1ImagesAnnotationsGet200Response,

    /**
     * The ApiV1ImagesAnnotationsGet200ResponseAnnotationsInner model constructor.
     * @property {module:model/ApiV1ImagesAnnotationsGet200ResponseAnnotationsInner}
     */
    ApiV1ImagesAnnotationsGet200ResponseAnnotationsInner,

    /**
     * The ApiV1ImagesAnnotationsGet200ResponseAnnotationsInnerTagsInner model constructor.
     * @property {module:model/ApiV1ImagesAnnotationsGet200ResponseAnnotationsInnerTagsInner}
     */
    ApiV1ImagesAnnotationsGet200ResponseAnnotationsInnerTagsInner,

    /**
     * The ApiV1LicensePost200Response model constructor.
     * @property {module:model/ApiV1LicensePost200Response}
     */
    ApiV1LicensePost200Response,

    /**
     * The ApiV1LocalizePost200Response model constructor.
     * @property {module:model/ApiV1LocalizePost200Response}
     */
    ApiV1LocalizePost200Response,

    /**
     * The ApiV1LocalizePost200ResponseResultsInner model constructor.
     * @property {module:model/ApiV1LocalizePost200ResponseResultsInner}
     */
    ApiV1LocalizePost200ResponseResultsInner,

    /**
     * The ApiV1LocalizePost200ResponseResultsInnerFileInner model constructor.
     * @property {module:model/ApiV1LocalizePost200ResponseResultsInnerFileInner}
     */
    ApiV1LocalizePost200ResponseResultsInnerFileInner,

    /**
     * The ApiV1LocalizePost200ResponseResultsInnerPredictionsInner model constructor.
     * @property {module:model/ApiV1LocalizePost200ResponseResultsInnerPredictionsInner}
     */
    ApiV1LocalizePost200ResponseResultsInnerPredictionsInner,

    /**
     * The ApiV1LocalizePost200ResponseResultsInnerPredictionsInnerBbox model constructor.
     * @property {module:model/ApiV1LocalizePost200ResponseResultsInnerPredictionsInnerBbox}
     */
    ApiV1LocalizePost200ResponseResultsInnerPredictionsInnerBbox,

    /**
     * The ApiV1MonitoringsBatchPut200Response model constructor.
     * @property {module:model/ApiV1MonitoringsBatchPut200Response}
     */
    ApiV1MonitoringsBatchPut200Response,

    /**
     * The ApiV1MonitoringsBatchPut200ResponseModifiedMonitoringsInner model constructor.
     * @property {module:model/ApiV1MonitoringsBatchPut200ResponseModifiedMonitoringsInner}
     */
    ApiV1MonitoringsBatchPut200ResponseModifiedMonitoringsInner,

    /**
     * The ApiV1MonitoringsBatchPutRequest model constructor.
     * @property {module:model/ApiV1MonitoringsBatchPutRequest}
     */
    ApiV1MonitoringsBatchPutRequest,

    /**
     * The ApiV1MonitoringsBatchPutRequestTaskUpdate model constructor.
     * @property {module:model/ApiV1MonitoringsBatchPutRequestTaskUpdate}
     */
    ApiV1MonitoringsBatchPutRequestTaskUpdate,

    /**
     * The ApiV1MonitoringsBatchPutRequestTaskUpdateDetection model constructor.
     * @property {module:model/ApiV1MonitoringsBatchPutRequestTaskUpdateDetection}
     */
    ApiV1MonitoringsBatchPutRequestTaskUpdateDetection,

    /**
     * The ApiV1MonitoringsBatchPutRequestTaskUpdateRegisteredEndpoint model constructor.
     * @property {module:model/ApiV1MonitoringsBatchPutRequestTaskUpdateRegisteredEndpoint}
     */
    ApiV1MonitoringsBatchPutRequestTaskUpdateRegisteredEndpoint,

    /**
     * The ApiV1MonitoringsGet200ResponseInner model constructor.
     * @property {module:model/ApiV1MonitoringsGet200ResponseInner}
     */
    ApiV1MonitoringsGet200ResponseInner,

    /**
     * The ApiV1MonitoringsGet200ResponseInnerRegion model constructor.
     * @property {module:model/ApiV1MonitoringsGet200ResponseInnerRegion}
     */
    ApiV1MonitoringsGet200ResponseInnerRegion,

    /**
     * The ApiV1MonitoringsGet200ResponseInnerSchedule model constructor.
     * @property {module:model/ApiV1MonitoringsGet200ResponseInnerSchedule}
     */
    ApiV1MonitoringsGet200ResponseInnerSchedule,

    /**
     * The ApiV1MonitoringsMonitoringIdDelete200Response model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdDelete200Response}
     */
    ApiV1MonitoringsMonitoringIdDelete200Response,

    /**
     * The ApiV1MonitoringsMonitoringIdGet200ResponseInner model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdGet200ResponseInner}
     */
    ApiV1MonitoringsMonitoringIdGet200ResponseInner,

    /**
     * The ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInner model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInner}
     */
    ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInner,

    /**
     * The ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerBbox model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerBbox}
     */
    ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerBbox,

    /**
     * The ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerScoresInner model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerScoresInner}
     */
    ApiV1MonitoringsMonitoringIdGet200ResponseInnerPredictionsInnerScoresInner,

    /**
     * The ApiV1MonitoringsMonitoringIdKillPost200Response model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdKillPost200Response}
     */
    ApiV1MonitoringsMonitoringIdKillPost200Response,

    /**
     * The ApiV1MonitoringsMonitoringIdProcessClipsPost200Response model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdProcessClipsPost200Response}
     */
    ApiV1MonitoringsMonitoringIdProcessClipsPost200Response,

    /**
     * The ApiV1MonitoringsMonitoringIdProcessClipsPost200ResponseTemporalTask model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdProcessClipsPost200ResponseTemporalTask}
     */
    ApiV1MonitoringsMonitoringIdProcessClipsPost200ResponseTemporalTask,

    /**
     * The ApiV1MonitoringsMonitoringIdPut200Response model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPut200Response}
     */
    ApiV1MonitoringsMonitoringIdPut200Response,

    /**
     * The ApiV1MonitoringsMonitoringIdPut200ResponseColors model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPut200ResponseColors}
     */
    ApiV1MonitoringsMonitoringIdPut200ResponseColors,

    /**
     * The ApiV1MonitoringsMonitoringIdPut200ResponseDetection model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPut200ResponseDetection}
     */
    ApiV1MonitoringsMonitoringIdPut200ResponseDetection,

    /**
     * The ApiV1MonitoringsMonitoringIdPut200ResponseDetectionMonitoringFilter model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPut200ResponseDetectionMonitoringFilter}
     */
    ApiV1MonitoringsMonitoringIdPut200ResponseDetectionMonitoringFilter,

    /**
     * The ApiV1MonitoringsMonitoringIdPut200ResponseRegion model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPut200ResponseRegion}
     */
    ApiV1MonitoringsMonitoringIdPut200ResponseRegion,

    /**
     * The ApiV1MonitoringsMonitoringIdPut200ResponseSchedule model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPut200ResponseSchedule}
     */
    ApiV1MonitoringsMonitoringIdPut200ResponseSchedule,

    /**
     * The ApiV1MonitoringsMonitoringIdPutRequest model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPutRequest}
     */
    ApiV1MonitoringsMonitoringIdPutRequest,

    /**
     * The ApiV1MonitoringsMonitoringIdPutRequestColors model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPutRequestColors}
     */
    ApiV1MonitoringsMonitoringIdPutRequestColors,

    /**
     * The ApiV1MonitoringsMonitoringIdPutRequestRegion model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPutRequestRegion}
     */
    ApiV1MonitoringsMonitoringIdPutRequestRegion,

    /**
     * The ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint}
     */
    ApiV1MonitoringsMonitoringIdPutRequestRegisteredEndpoint,

    /**
     * The ApiV1MonitoringsMonitoringIdPutRequestSchedule model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdPutRequestSchedule}
     */
    ApiV1MonitoringsMonitoringIdPutRequestSchedule,

    /**
     * The ApiV1MonitoringsMonitoringIdWatchGet200Response model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdWatchGet200Response}
     */
    ApiV1MonitoringsMonitoringIdWatchGet200Response,

    /**
     * The ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInner model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInner}
     */
    ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInner,

    /**
     * The ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerBbox model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerBbox}
     */
    ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerBbox,

    /**
     * The ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerScoresInner model constructor.
     * @property {module:model/ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerScoresInner}
     */
    ApiV1MonitoringsMonitoringIdWatchGet200ResponseDetectionsInnerScoresInner,

    /**
     * The ApiV1OauthTokenPost200Response model constructor.
     * @property {module:model/ApiV1OauthTokenPost200Response}
     */
    ApiV1OauthTokenPost200Response,

    /**
     * The ApiV1StreamsBatchPost200ResponseValue model constructor.
     * @property {module:model/ApiV1StreamsBatchPost200ResponseValue}
     */
    ApiV1StreamsBatchPost200ResponseValue,

    /**
     * The ApiV1StreamsBatchPost200ResponseValueMonitoring model constructor.
     * @property {module:model/ApiV1StreamsBatchPost200ResponseValueMonitoring}
     */
    ApiV1StreamsBatchPost200ResponseValueMonitoring,

    /**
     * The ApiV1StreamsBatchPost200ResponseValueStream model constructor.
     * @property {module:model/ApiV1StreamsBatchPost200ResponseValueStream}
     */
    ApiV1StreamsBatchPost200ResponseValueStream,

    /**
     * The ApiV1StreamsBatchPostRequest1 model constructor.
     * @property {module:model/ApiV1StreamsBatchPostRequest1}
     */
    ApiV1StreamsBatchPostRequest1,

    /**
     * The ApiV1StreamsBatchPostRequest1DetectorsInner model constructor.
     * @property {module:model/ApiV1StreamsBatchPostRequest1DetectorsInner}
     */
    ApiV1StreamsBatchPostRequest1DetectorsInner,

    /**
     * The ApiV1StreamsBatchPostRequest1StreamsInner model constructor.
     * @property {module:model/ApiV1StreamsBatchPostRequest1StreamsInner}
     */
    ApiV1StreamsBatchPostRequest1StreamsInner,

    /**
     * The ApiV1StreamsBatchPostRequest1StreamsInnerCustomFieldsInner model constructor.
     * @property {module:model/ApiV1StreamsBatchPostRequest1StreamsInnerCustomFieldsInner}
     */
    ApiV1StreamsBatchPostRequest1StreamsInnerCustomFieldsInner,

    /**
     * The ApiV1StreamsGet200ResponseInner model constructor.
     * @property {module:model/ApiV1StreamsGet200ResponseInner}
     */
    ApiV1StreamsGet200ResponseInner,

    /**
     * The ApiV1StreamsGet200ResponseInnerRecordingOptions model constructor.
     * @property {module:model/ApiV1StreamsGet200ResponseInnerRecordingOptions}
     */
    ApiV1StreamsGet200ResponseInnerRecordingOptions,

    /**
     * The ApiV1StreamsPost200Response model constructor.
     * @property {module:model/ApiV1StreamsPost200Response}
     */
    ApiV1StreamsPost200Response,

    /**
     * The ApiV1StreamsPostRequest model constructor.
     * @property {module:model/ApiV1StreamsPostRequest}
     */
    ApiV1StreamsPostRequest,

    /**
     * The ApiV1StreamsPostRequestCustomFieldsInner model constructor.
     * @property {module:model/ApiV1StreamsPostRequestCustomFieldsInner}
     */
    ApiV1StreamsPostRequestCustomFieldsInner,

    /**
     * The ApiV1StreamsStreamIdClipsGet200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdClipsGet200Response}
     */
    ApiV1StreamsStreamIdClipsGet200Response,

    /**
     * The ApiV1StreamsStreamIdClipsGet200ResponseClipsInner model constructor.
     * @property {module:model/ApiV1StreamsStreamIdClipsGet200ResponseClipsInner}
     */
    ApiV1StreamsStreamIdClipsGet200ResponseClipsInner,

    /**
     * The ApiV1StreamsStreamIdDelete200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdDelete200Response}
     */
    ApiV1StreamsStreamIdDelete200Response,

    /**
     * The ApiV1StreamsStreamIdMonitorDetectorIdPost200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdMonitorDetectorIdPost200Response}
     */
    ApiV1StreamsStreamIdMonitorDetectorIdPost200Response,

    /**
     * The ApiV1StreamsStreamIdMonitorDetectorIdPostRequest model constructor.
     * @property {module:model/ApiV1StreamsStreamIdMonitorDetectorIdPostRequest}
     */
    ApiV1StreamsStreamIdMonitorDetectorIdPostRequest,

    /**
     * The ApiV1StreamsStreamIdMonitorDetectorIdPostRequestColors model constructor.
     * @property {module:model/ApiV1StreamsStreamIdMonitorDetectorIdPostRequestColors}
     */
    ApiV1StreamsStreamIdMonitorDetectorIdPostRequestColors,

    /**
     * The ApiV1StreamsStreamIdMonitorDetectorIdPostRequestMonitoringHoursInner model constructor.
     * @property {module:model/ApiV1StreamsStreamIdMonitorDetectorIdPostRequestMonitoringHoursInner}
     */
    ApiV1StreamsStreamIdMonitorDetectorIdPostRequestMonitoringHoursInner,

    /**
     * The ApiV1StreamsStreamIdPushImagePost200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdPushImagePost200Response}
     */
    ApiV1StreamsStreamIdPushImagePost200Response,

    /**
     * The ApiV1StreamsStreamIdPushImagePost400Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdPushImagePost400Response}
     */
    ApiV1StreamsStreamIdPushImagePost400Response,

    /**
     * The ApiV1StreamsStreamIdPushVideoPost200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdPushVideoPost200Response}
     */
    ApiV1StreamsStreamIdPushVideoPost200Response,

    /**
     * The ApiV1StreamsStreamIdPut200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdPut200Response}
     */
    ApiV1StreamsStreamIdPut200Response,

    /**
     * The ApiV1StreamsStreamIdPut200ResponseCustomFieldsInner model constructor.
     * @property {module:model/ApiV1StreamsStreamIdPut200ResponseCustomFieldsInner}
     */
    ApiV1StreamsStreamIdPut200ResponseCustomFieldsInner,

    /**
     * The ApiV1StreamsStreamIdPutRequest model constructor.
     * @property {module:model/ApiV1StreamsStreamIdPutRequest}
     */
    ApiV1StreamsStreamIdPutRequest,

    /**
     * The ApiV1StreamsStreamIdPutRequestLocation model constructor.
     * @property {module:model/ApiV1StreamsStreamIdPutRequestLocation}
     */
    ApiV1StreamsStreamIdPutRequestLocation,

    /**
     * The ApiV1StreamsStreamIdSampleStreamPost200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdSampleStreamPost200Response}
     */
    ApiV1StreamsStreamIdSampleStreamPost200Response,

    /**
     * The ApiV1StreamsStreamIdSampleStreamPost200ResponseTemporalTask model constructor.
     * @property {module:model/ApiV1StreamsStreamIdSampleStreamPost200ResponseTemporalTask}
     */
    ApiV1StreamsStreamIdSampleStreamPost200ResponseTemporalTask,

    /**
     * The ApiV1StreamsStreamIdSummariesGet200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdSummariesGet200Response}
     */
    ApiV1StreamsStreamIdSummariesGet200Response,

    /**
     * The ApiV1StreamsStreamIdSummariesGet200ResponseSummariesInner model constructor.
     * @property {module:model/ApiV1StreamsStreamIdSummariesGet200ResponseSummariesInner}
     */
    ApiV1StreamsStreamIdSummariesGet200ResponseSummariesInner,

    /**
     * The ApiV1StreamsStreamIdSummarizePost200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdSummarizePost200Response}
     */
    ApiV1StreamsStreamIdSummarizePost200Response,

    /**
     * The ApiV1StreamsStreamIdSummarizePost200ResponseSummary model constructor.
     * @property {module:model/ApiV1StreamsStreamIdSummarizePost200ResponseSummary}
     */
    ApiV1StreamsStreamIdSummarizePost200ResponseSummary,

    /**
     * The ApiV1StreamsStreamIdTemporalTaskPost200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdTemporalTaskPost200Response}
     */
    ApiV1StreamsStreamIdTemporalTaskPost200Response,

    /**
     * The ApiV1StreamsStreamIdTemporalTasksGet200Response model constructor.
     * @property {module:model/ApiV1StreamsStreamIdTemporalTasksGet200Response}
     */
    ApiV1StreamsStreamIdTemporalTasksGet200Response,

    /**
     * The ApiV1StreamsStreamIdTemporalTasksGet200ResponseTemporalTasksInner model constructor.
     * @property {module:model/ApiV1StreamsStreamIdTemporalTasksGet200ResponseTemporalTasksInner}
     */
    ApiV1StreamsStreamIdTemporalTasksGet200ResponseTemporalTasksInner,

    /**
     * The ApiV1SummariesGet200Response model constructor.
     * @property {module:model/ApiV1SummariesGet200Response}
     */
    ApiV1SummariesGet200Response,

    /**
     * The ApiV1SummariesGet200ResponseSummariesInner model constructor.
     * @property {module:model/ApiV1SummariesGet200ResponseSummariesInner}
     */
    ApiV1SummariesGet200ResponseSummariesInner,

    /**
     * The ApiV1SummariesSummaryIdDelete200Response model constructor.
     * @property {module:model/ApiV1SummariesSummaryIdDelete200Response}
     */
    ApiV1SummariesSummaryIdDelete200Response,

    /**
     * The ApiV1SummariesSummaryIdGet200Response model constructor.
     * @property {module:model/ApiV1SummariesSummaryIdGet200Response}
     */
    ApiV1SummariesSummaryIdGet200Response,

    /**
     * The ApiV1SystemStatusGet200Response model constructor.
     * @property {module:model/ApiV1SystemStatusGet200Response}
     */
    ApiV1SystemStatusGet200Response,

    /**
     * The ApiV1SystemStatusGet200ResponseDownMonitoringsInner model constructor.
     * @property {module:model/ApiV1SystemStatusGet200ResponseDownMonitoringsInner}
     */
    ApiV1SystemStatusGet200ResponseDownMonitoringsInner,

    /**
     * The ApiV1SystemStatusGet200ResponseDownMonitoringsInnerDetector model constructor.
     * @property {module:model/ApiV1SystemStatusGet200ResponseDownMonitoringsInnerDetector}
     */
    ApiV1SystemStatusGet200ResponseDownMonitoringsInnerDetector,

    /**
     * The ApiV1SystemStatusGet200ResponseDownMonitoringsInnerStream model constructor.
     * @property {module:model/ApiV1SystemStatusGet200ResponseDownMonitoringsInnerStream}
     */
    ApiV1SystemStatusGet200ResponseDownMonitoringsInnerStream,

    /**
     * The ApiV1TemporalTasksGet200Response model constructor.
     * @property {module:model/ApiV1TemporalTasksGet200Response}
     */
    ApiV1TemporalTasksGet200Response,

    /**
     * The ApiV1TemporalTasksGet200ResponseTemporalTasksInner model constructor.
     * @property {module:model/ApiV1TemporalTasksGet200ResponseTemporalTasksInner}
     */
    ApiV1TemporalTasksGet200ResponseTemporalTasksInner,

    /**
     * The ApiV1TemporalTasksTaskIdDelete200Response model constructor.
     * @property {module:model/ApiV1TemporalTasksTaskIdDelete200Response}
     */
    ApiV1TemporalTasksTaskIdDelete200Response,

    /**
     * The ApiV1TemporalTasksTaskIdGet200Response model constructor.
     * @property {module:model/ApiV1TemporalTasksTaskIdGet200Response}
     */
    ApiV1TemporalTasksTaskIdGet200Response,

    /**
     * The ApiV1TemporalTasksTaskIdKillPut200Response model constructor.
     * @property {module:model/ApiV1TemporalTasksTaskIdKillPut200Response}
     */
    ApiV1TemporalTasksTaskIdKillPut200Response,

    /**
     * The ApiV1TestUsersPost200Response model constructor.
     * @property {module:model/ApiV1TestUsersPost200Response}
     */
    ApiV1TestUsersPost200Response,

    /**
     * The ApiV1TestUsersUserIdDelete200Response model constructor.
     * @property {module:model/ApiV1TestUsersUserIdDelete200Response}
     */
    ApiV1TestUsersUserIdDelete200Response,

    /**
     * The ApiV1VideosVideoIdGet200Response model constructor.
     * @property {module:model/ApiV1VideosVideoIdGet200Response}
     */
    ApiV1VideosVideoIdGet200Response,

    /**
     * The ApiV1VideosVideoIdGet200ResponseDetectionsValueInner model constructor.
     * @property {module:model/ApiV1VideosVideoIdGet200ResponseDetectionsValueInner}
     */
    ApiV1VideosVideoIdGet200ResponseDetectionsValueInner,

    /**
     * The ApiV1VideosVideoIdGet200ResponseDetectionsValueInnerBbox model constructor.
     * @property {module:model/ApiV1VideosVideoIdGet200ResponseDetectionsValueInnerBbox}
     */
    ApiV1VideosVideoIdGet200ResponseDetectionsValueInnerBbox,

    /**
     * The CreateDetector200Response model constructor.
     * @property {module:model/CreateDetector200Response}
     */
    CreateDetector200Response,

    /**
    * The AccountsApi service constructor.
    * @property {module:api/AccountsApi}
    */
    AccountsApi,

    /**
    * The BucketTasksApi service constructor.
    * @property {module:api/BucketTasksApi}
    */
    BucketTasksApi,

    /**
    * The DatasetApi service constructor.
    * @property {module:api/DatasetApi}
    */
    DatasetApi,

    /**
    * The DetectorsApi service constructor.
    * @property {module:api/DetectorsApi}
    */
    DetectorsApi,

    /**
    * The ImagesApi service constructor.
    * @property {module:api/ImagesApi}
    */
    ImagesApi,

    /**
    * The LabelsApi service constructor.
    * @property {module:api/LabelsApi}
    */
    LabelsApi,

    /**
    * The LicensesApi service constructor.
    * @property {module:api/LicensesApi}
    */
    LicensesApi,

    /**
    * The MonitoringsApi service constructor.
    * @property {module:api/MonitoringsApi}
    */
    MonitoringsApi,

    /**
    * The OnPremApi service constructor.
    * @property {module:api/OnPremApi}
    */
    OnPremApi,

    /**
    * The SimilaritySearchApi service constructor.
    * @property {module:api/SimilaritySearchApi}
    */
    SimilaritySearchApi,

    /**
    * The StreamsApi service constructor.
    * @property {module:api/StreamsApi}
    */
    StreamsApi,

    /**
    * The TemporalTaskApi service constructor.
    * @property {module:api/TemporalTaskApi}
    */
    TemporalTaskApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The VideoSummaryApi service constructor.
    * @property {module:api/VideoSummaryApi}
    */
    VideoSummaryApi,

    /**
    * The VideosApi service constructor.
    * @property {module:api/VideosApi}
    */
    VideosApi
};
